In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from main import Sequential, Dense, accuracy

In [2]:
data = pd.read_csv("mnist_data.csv")

In [3]:
X = data.drop(columns=['label'])
y = data['label']
y = pd.get_dummies(y)
X  = X/255.0
X = X.to_numpy()
y = y.to_numpy().astype(np.float32)

In [4]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [5]:

model = Sequential([
    Dense(16),
    Dense(16),
    Dense(10, activation='softmax')
])
model.compile(loss='sparse_categorical_cross_entropy')

In [ ]:
model.fit(X, y, epochs=500, learning_rate=0.01)

Epoch: 1, Accuracy: 0.9080952380952381, sparse_categorical_cross_entropy loss: 0.3261069796779409
Epoch: 2, Accuracy: 0.9080952380952381, sparse_categorical_cross_entropy loss: 0.3260875314079049
Epoch: 3, Accuracy: 0.9081428571428571, sparse_categorical_cross_entropy loss: 0.32606808789920405
Epoch: 4, Accuracy: 0.9081428571428571, sparse_categorical_cross_entropy loss: 0.3260486520514867
Epoch: 5, Accuracy: 0.9081190476190476, sparse_categorical_cross_entropy loss: 0.32602922485414
Epoch: 6, Accuracy: 0.9081190476190476, sparse_categorical_cross_entropy loss: 0.3260098036742513
Epoch: 7, Accuracy: 0.9081190476190476, sparse_categorical_cross_entropy loss: 0.325990389578025
Epoch: 8, Accuracy: 0.9081190476190476, sparse_categorical_cross_entropy loss: 0.325970986841061
Epoch: 9, Accuracy: 0.9081190476190476, sparse_categorical_cross_entropy loss: 0.325951591182915
Epoch: 10, Accuracy: 0.9081190476190476, sparse_categorical_cross_entropy loss: 0.3259321968176845
Epoch: 11, Accuracy: 0.

In [7]:
y_pred = model.predict(X[:10])

In [8]:
np.argmax(y_pred, axis=1, keepdims=True)

array([[9],
       [7],
       [3],
       [7],
       [0],
       [7],
       [7],
       [3],
       [3],
       [3]])

In [9]:
np.argmax(y[:10], axis=1, keepdims=True)

array([[1],
       [0],
       [1],
       [4],
       [0],
       [0],
       [7],
       [3],
       [5],
       [3]])

In [18]:
# import tensorflow as tf
X.shape

(42000, 784)

In [19]:
tfmodel = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])
tfmodel.compile(loss=tf.keras.losses.CategoricalCrossentropy, metrics=['accuracy'])

In [21]:
tfmodel.fit(X, y, epochs=10)

Epoch 1/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9263 - loss: 0.2570
Epoch 2/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9404 - loss: 0.2068
Epoch 3/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9460 - loss: 0.1904
Epoch 4/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9509 - loss: 0.1702
Epoch 5/10
 194/1313 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9492 - loss: 0.1823

KeyboardInterrupt: 